name: ZAP
on:
  push:
  workflow_dispatch:
  # schedule:
  #   # Runs every day At 08:30 EST
  #   - cron:  '30 13 * * *'
  inputs:
    url:
      description: 'url to test'
      required: true

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan SLIMMTech website
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: ${{ github.event.inputs.url }}
